# Generated by Django 4.0.6 on 2022-08-03 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='is_ative',
            new_name='is_active',
        ),
    ]
